//
//  VIPER-Router.swift
//  architectures
//
//  Created YutoMizutani on 2018/06/06.
//  Copyright © 2018 Yuto Mizutani. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VIPERRouter: VIPERWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        let view = VIPERViewController()
        let interactor = VIPERInteractor()
        let router = VIPERRouter()
        let presenter = VIPERPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
