//
//  VIPER-Interactor.swift
//  architectures
//
//  Created YutoMizutani on 2018/06/06.
//  Copyright © 2018 Yuto Mizutani. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

/*
 
 Interactor
     このオブジェクトは特定のModuleのユースケースを集めた物と考えられます。
     Interactorは関連するEntityを全て含み、UIとは完全に分離するはずです。

 [iOS Project Architecture : Using VIPER [和訳]](https://qiita.com/YKEI_mrn/items/67735d8ebc9a83fffd29)より

 */

import UIKit

class VIPERInteractor {
    weak var presenter: VIPERInteractorOutputProtocol?
}

// MARK:- Public methods accessed from other classes
extension VIPERInteractor: VIPERInteractorInputProtocol {
    /**
     Entityを取得する。

     - returns:
        ユーザー情報
     - throws:
        ユーザーが存在しなかった場合
     */
    public func fetchEntity() throws -> [VIPEREntity] {
        // Userを取得する
        guard let dictionary = self.fetch() else { throw ErrorTransfer.userNotFound }

        // Entity型に変換して返す。
        return try self.translate(dictionary)
    }

    /**
     指定されたユーザーの初期化を行う。

     - Parameters:
        - user: ユーザー情報

     - returns:
        ユーザー情報
     */
    public func reset(_ collections: [VIPEREntity]) -> [VIPEREntity] {
        // 初期化を行う。
        let newCollections = self.getInitValue(collections)

        // 保存する。
        self.commit(newCollections)

        return newCollections
    }

    /**
     ユーザー情報の更新を行う。

     - Parameters:
        - collections: ユーザー情報
     */
    public func commit(_ collections: [VIPEREntity]) {
        // dictionary型に変換して保存する。
        let dictionary = self.translate(collections)
        self.update(dictionary)
    }

    /**
     入金処理を行う

     - Parameters:
        - to: ユーザー情報
        - amount: 金額

     - throws: Intの最大値を超過する場合
     */
    public func credit(_ to: VIPEREntity, amount: Int) throws -> VIPEREntity {
        // 入金後の残高がIntの最大値を超過するかの判断を行う
        if to.balance > Int.max - amount {
            throw ErrorTransfer.amountOverflow
        }

        // 金額を加算する。
        return VIPEREntity(user: to.user, balance: to.balance + amount)
    }

    /**
     出金処理を行う

     - Parameters:
        - from: ユーザー情報
        - amount: 金額

     - throws: 0を下回る場合
     */
    public func debit(_ from: VIPEREntity, amount: Int) throws -> VIPEREntity {
        // 出金後の残高が0を下回るかの判断を行う
        if from.balance - amount < 0 {
            throw ErrorTransfer.insufficientFunds
        }

        // 金額を減算する。
        return VIPEREntity(user: from.user, balance: from.balance - amount)
    }
}

// MARK:- Private methods about business logics

// MARK:- Private methods about initialize
extension VIPERInteractor {
    /**
     指定されたユーザーの初期化を行う。

     - Parameters:
        - collections: ユーザー情報

     - returns:
        ユーザー情報
     */
    private func getInitValue(_ collections: [VIPEREntity]) -> [VIPEREntity] {
        let users = collections.map{ $0.user }

        return users.map{ VIPEREntity(user: $0, balance: $0.initValue) }
    }
}

// MARK:- Private methods about translate
extension VIPERInteractor {
    /**
     UserDefaultsから取得したデータをEntityに変換する。

     - Parameters:
        - dictionary: Dictionary型のユーザー情報

     - returns:
        Entity型のユーザー情報

     - throws:
        ユーザーが見つからなかった場合，型変換に失敗した場合
     */
    private func translate(_ dictionary: Dictionary<String, Any>) throws -> [VIPEREntity] {
        var entities: [VIPEREntity] = []

        for d in dictionary {

            // ユーザーを検索する。
            guard let user = UserList.find(d.key) else {
                throw ErrorTransfer.userNotFound
            }

            // AnyをIntに変換する。
            guard let balance = d.value as? Int else {
                throw ErrorTransfer.storedTypeInvalid
            }

            // Factoryを元に生成する。
            let entity = VIPEREntity(user: user, balance: balance)

            entities.append(entity)
        }

        return entities
    }

    /**
     UserDefaultsから取得したデータをEntityに変換する。

     - Parameters:
        - entities: Entity型のユーザー情報

     - returns:
        Dictionary型のユーザー情報
     */
    private func translate(_ entities: [VIPEREntity]) -> Dictionary<String, Any> {
        var dictionary = Dictionary<String, Any>()

        for c in entities {
            dictionary[c.user.rawValue] = c.balance
        }

        return dictionary
    }
}

// MARK:- Private methods about userdefaults
extension VIPERInteractor {
    /**
     UserDefaultsからデータを取得する。

     - returns:
        Dictionary型のユーザー情報
     */
    private func fetch() -> Dictionary<String, Any>? {
        let userDefaults: UserDefaults = UserDefaults.standard
        let key = UserDefaultsKeys.account.rawValue

        return userDefaults.dictionary(forKey: key)
    }


    /**
     UserDefaultsへデータを保存する。

     - Parameters:
        - dictionary: Dictionary型のユーザー情報
     */
    private func update(_ dictionary: Dictionary<String, Any>) {
        let userDefaults: UserDefaults = UserDefaults.standard
        let key = UserDefaultsKeys.account.rawValue

        userDefaults.set(dictionary, forKey: key)
    }
}
