//
//  VIPER-ViewController.swift
//  architectures
//
//  Created YutoMizutani on 2018/06/06.
//  Copyright © 2018 Yuto Mizutani. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VIPERViewController: UIViewController, VIPERViewProtocol {

	var presenter: VIPERPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
