//
//  VIPER-Presenter.swift
//  architectures
//
//  Created YutoMizutani on 2018/06/06.
//  Copyright © 2018 Yuto Mizutani. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VIPERPresenter: VIPERPresenterProtocol, VIPERInteractorOutputProtocol {

    weak private var view: VIPERViewProtocol?
    var interactor: VIPERInteractorInputProtocol?
    private let router: VIPERWireframeProtocol

    init(interface: VIPERViewProtocol, interactor: VIPERInteractorInputProtocol?, router: VIPERWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
