//
//  VIPER-Protocols.swift
//  architectures
//
//  Created YutoMizutani on 2018/06/06.
//  Copyright © 2018 Yuto Mizutani. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol VIPERWireframeProtocol: class {

}
//MARK: Presenter -
protocol VIPERPresenterProtocol: class {

    var interactor: VIPERInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol VIPERInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol VIPERInteractorInputProtocol: class {

    var presenter: VIPERInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol VIPERViewProtocol: class {

    var presenter: VIPERPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
